
requires = ["hatchling"]
build-backend = "hatchling.build"


name = "example_package_gaellemc"
version = "0.0.1"
authors = [
  { name="example_package_gaellemc", email="gaelle.monteil-combabessou@isen.yncrea.fr" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

